#!/bin/bash

if [ "$1" = "-r" ];then
    xrandr --output HDMI-2 --off
    xrandr --output DP-1 --off
    sleep 5
else
    # config in MPK
    # xrandr --output DP-1 --auto --above eDP-1 --output HDMI-2 --auto --left-of DP-1 --rotate left

    # config in MPK/apt
    # xrandr --output DP-1 --auto --above eDP-1 

    # config for curved monitor
    xrandr --output HDMI-2 --auto --output eDP-1 --left-of HDMI-2 --auto
fi
